server:
        port: 9090
        context-path: /validaprocessamento          
debug:
    false 
spring:
    application:
        name: validaprocessamento
        
    datasource:
        url: jdbc:mysql://${ip_banco}:3306/validaprocessamento?autoReconnect=true
        username: root
        password: ro0t
        driverClassName: com.mysql.jdbc.Driver
        connectionTestQuery: SELECT 1 FROM DUAL
        test-while-idle: true
        test-on-borrow: true
        validation-query: SELECT 1
        time-between-eviction-runs-millis: 5000
        min-evictable-idle-time-millis: 60000
        
    jpa:
        database: MYSQL
        show-sql: false
        hibernate:
            ddl-auto: none