server:
        port: 9090
        context-path: /validaprocessamento          
debug:
    false 
spring:
    application:
        name: validaprocessamento
        
    datasource:
        url: jdbc:mysql://${ip_banco}:3306/validaprocessamento?autoReconnect=true
        username: root
        password: ro0t
        driverClassName: com.mysql.jdbc.Driver
        connectionTestQuery: SELECT 1 FROM DUAL
        
    jpa:
        database: MYSQL
        show-sql: false
        hibernate:
            ddl-auto: update